/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GoodbyeRouteImport } from './routes/goodbye'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedCreateTeamRouteImport } from './routes/_authenticated/create-team'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/_team'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/_coach'
import { Route as AuthenticatedWorkoutsIndexRouteImport } from './routes/_authenticated/workouts.index'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team/index'
import { Route as AuthenticatedWorkoutsWorkoutIdRouteImport } from './routes/_authenticated/workouts.$workoutId'
import { Route as AuthenticatedTeamIdentifierRouteImport } from './routes/_authenticated/team/$identifier'
import { Route as AuthenticatedTeamAthletesRouteImport } from './routes/_authenticated/_team/athletes'
import { Route as AuthenticatedCoachWhiteboardRouteImport } from './routes/_authenticated/_coach/whiteboard'
import { Route as AuthenticatedCoachTrainingRouteImport } from './routes/_authenticated/_coach/training'
import { Route as AuthenticatedCoachSeatRacingRouteImport } from './routes/_authenticated/_coach/seat-racing'
import { Route as AuthenticatedCoachRecruitingRouteImport } from './routes/_authenticated/_coach/recruiting'
import { Route as AuthenticatedCoachLineupBuilderRouteImport } from './routes/_authenticated/_coach/lineup-builder'
import { Route as AuthenticatedCoachFleetRouteImport } from './routes/_authenticated/_coach/fleet'
import { Route as AuthenticatedCoachAttendanceRouteImport } from './routes/_authenticated/_coach/attendance'
import { Route as AuthenticatedTeamIdentifierSettingsRouteImport } from './routes/_authenticated/team/$identifier/settings'
import { Route as AuthenticatedTeamIdentifierDashboardRouteImport } from './routes/_authenticated/team/$identifier/dashboard'
import { Route as AuthenticatedCoachTrainingSessionsRouteImport } from './routes/_authenticated/_coach/training_.sessions'
import { Route as AuthenticatedCoachTrainingSessionsSessionIdRouteImport } from './routes/_authenticated/_coach/training_.sessions.$sessionId'
import { Route as AuthenticatedCoachTrainingSessionsSessionIdLiveRouteImport } from './routes/_authenticated/_coach/training_.sessions.$sessionId.live'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodbyeRoute = GoodbyeRouteImport.update({
  id: '/goodbye',
  path: '/goodbye',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateTeamRoute = AuthenticatedCreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/_team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/_coach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkoutsIndexRoute =
  AuthenticatedWorkoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkoutsWorkoutIdRoute =
  AuthenticatedWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedTeamIdentifierRoute =
  AuthenticatedTeamIdentifierRouteImport.update({
    id: '/team/$identifier',
    path: '/team/$identifier',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamAthletesRoute =
  AuthenticatedTeamAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedTeamRoute,
  } as any)
const AuthenticatedCoachWhiteboardRoute =
  AuthenticatedCoachWhiteboardRouteImport.update({
    id: '/whiteboard',
    path: '/whiteboard',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachTrainingRoute =
  AuthenticatedCoachTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachSeatRacingRoute =
  AuthenticatedCoachSeatRacingRouteImport.update({
    id: '/seat-racing',
    path: '/seat-racing',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachRecruitingRoute =
  AuthenticatedCoachRecruitingRouteImport.update({
    id: '/recruiting',
    path: '/recruiting',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachLineupBuilderRoute =
  AuthenticatedCoachLineupBuilderRouteImport.update({
    id: '/lineup-builder',
    path: '/lineup-builder',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachFleetRoute = AuthenticatedCoachFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedCoachRoute,
} as any)
const AuthenticatedCoachAttendanceRoute =
  AuthenticatedCoachAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedTeamIdentifierSettingsRoute =
  AuthenticatedTeamIdentifierSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTeamIdentifierRoute,
  } as any)
const AuthenticatedTeamIdentifierDashboardRoute =
  AuthenticatedTeamIdentifierDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedTeamIdentifierRoute,
  } as any)
const AuthenticatedCoachTrainingSessionsRoute =
  AuthenticatedCoachTrainingSessionsRouteImport.update({
    id: '/training_/sessions',
    path: '/training/sessions',
    getParentRoute: () => AuthenticatedCoachRoute,
  } as any)
const AuthenticatedCoachTrainingSessionsSessionIdRoute =
  AuthenticatedCoachTrainingSessionsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedCoachTrainingSessionsRoute,
  } as any)
const AuthenticatedCoachTrainingSessionsSessionIdLiveRoute =
  AuthenticatedCoachTrainingSessionsSessionIdLiveRouteImport.update({
    id: '/live',
    path: '/live',
    getParentRoute: () => AuthenticatedCoachTrainingSessionsSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/goodbye': typeof GoodbyeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/create-team': typeof AuthenticatedCreateTeamRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/attendance': typeof AuthenticatedCoachAttendanceRoute
  '/fleet': typeof AuthenticatedCoachFleetRoute
  '/lineup-builder': typeof AuthenticatedCoachLineupBuilderRoute
  '/recruiting': typeof AuthenticatedCoachRecruitingRoute
  '/seat-racing': typeof AuthenticatedCoachSeatRacingRoute
  '/training': typeof AuthenticatedCoachTrainingRoute
  '/whiteboard': typeof AuthenticatedCoachWhiteboardRoute
  '/athletes': typeof AuthenticatedTeamAthletesRoute
  '/team/$identifier': typeof AuthenticatedTeamIdentifierRouteWithChildren
  '/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/training/sessions': typeof AuthenticatedCoachTrainingSessionsRouteWithChildren
  '/team/$identifier/dashboard': typeof AuthenticatedTeamIdentifierDashboardRoute
  '/team/$identifier/settings': typeof AuthenticatedTeamIdentifierSettingsRoute
  '/training/sessions/$sessionId': typeof AuthenticatedCoachTrainingSessionsSessionIdRouteWithChildren
  '/training/sessions/$sessionId/live': typeof AuthenticatedCoachTrainingSessionsSessionIdLiveRoute
}
export interface FileRoutesByTo {
  '/goodbye': typeof GoodbyeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/create-team': typeof AuthenticatedCreateTeamRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/attendance': typeof AuthenticatedCoachAttendanceRoute
  '/fleet': typeof AuthenticatedCoachFleetRoute
  '/lineup-builder': typeof AuthenticatedCoachLineupBuilderRoute
  '/recruiting': typeof AuthenticatedCoachRecruitingRoute
  '/seat-racing': typeof AuthenticatedCoachSeatRacingRoute
  '/training': typeof AuthenticatedCoachTrainingRoute
  '/whiteboard': typeof AuthenticatedCoachWhiteboardRoute
  '/athletes': typeof AuthenticatedTeamAthletesRoute
  '/team/$identifier': typeof AuthenticatedTeamIdentifierRouteWithChildren
  '/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/workouts': typeof AuthenticatedWorkoutsIndexRoute
  '/training/sessions': typeof AuthenticatedCoachTrainingSessionsRouteWithChildren
  '/team/$identifier/dashboard': typeof AuthenticatedTeamIdentifierDashboardRoute
  '/team/$identifier/settings': typeof AuthenticatedTeamIdentifierSettingsRoute
  '/training/sessions/$sessionId': typeof AuthenticatedCoachTrainingSessionsSessionIdRouteWithChildren
  '/training/sessions/$sessionId/live': typeof AuthenticatedCoachTrainingSessionsSessionIdLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/goodbye': typeof GoodbyeRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_coach': typeof AuthenticatedCoachRouteWithChildren
  '/_authenticated/_team': typeof AuthenticatedTeamRouteWithChildren
  '/_authenticated/create-team': typeof AuthenticatedCreateTeamRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_coach/attendance': typeof AuthenticatedCoachAttendanceRoute
  '/_authenticated/_coach/fleet': typeof AuthenticatedCoachFleetRoute
  '/_authenticated/_coach/lineup-builder': typeof AuthenticatedCoachLineupBuilderRoute
  '/_authenticated/_coach/recruiting': typeof AuthenticatedCoachRecruitingRoute
  '/_authenticated/_coach/seat-racing': typeof AuthenticatedCoachSeatRacingRoute
  '/_authenticated/_coach/training': typeof AuthenticatedCoachTrainingRoute
  '/_authenticated/_coach/whiteboard': typeof AuthenticatedCoachWhiteboardRoute
  '/_authenticated/_team/athletes': typeof AuthenticatedTeamAthletesRoute
  '/_authenticated/team/$identifier': typeof AuthenticatedTeamIdentifierRouteWithChildren
  '/_authenticated/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/_authenticated/_coach/training_/sessions': typeof AuthenticatedCoachTrainingSessionsRouteWithChildren
  '/_authenticated/team/$identifier/dashboard': typeof AuthenticatedTeamIdentifierDashboardRoute
  '/_authenticated/team/$identifier/settings': typeof AuthenticatedTeamIdentifierSettingsRoute
  '/_authenticated/_coach/training_/sessions/$sessionId': typeof AuthenticatedCoachTrainingSessionsSessionIdRouteWithChildren
  '/_authenticated/_coach/training_/sessions/$sessionId/live': typeof AuthenticatedCoachTrainingSessionsSessionIdLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goodbye'
    | '/login'
    | '/register'
    | '/create-team'
    | '/profile'
    | '/settings'
    | '/workouts'
    | '/invite/$code'
    | '/attendance'
    | '/fleet'
    | '/lineup-builder'
    | '/recruiting'
    | '/seat-racing'
    | '/training'
    | '/whiteboard'
    | '/athletes'
    | '/team/$identifier'
    | '/workouts/$workoutId'
    | '/team/'
    | '/workouts/'
    | '/training/sessions'
    | '/team/$identifier/dashboard'
    | '/team/$identifier/settings'
    | '/training/sessions/$sessionId'
    | '/training/sessions/$sessionId/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/goodbye'
    | '/login'
    | '/register'
    | '/'
    | '/create-team'
    | '/profile'
    | '/settings'
    | '/invite/$code'
    | '/attendance'
    | '/fleet'
    | '/lineup-builder'
    | '/recruiting'
    | '/seat-racing'
    | '/training'
    | '/whiteboard'
    | '/athletes'
    | '/team/$identifier'
    | '/workouts/$workoutId'
    | '/team'
    | '/workouts'
    | '/training/sessions'
    | '/team/$identifier/dashboard'
    | '/team/$identifier/settings'
    | '/training/sessions/$sessionId'
    | '/training/sessions/$sessionId/live'
  id:
    | '__root__'
    | '/_authenticated'
    | '/goodbye'
    | '/login'
    | '/register'
    | '/_authenticated/_coach'
    | '/_authenticated/_team'
    | '/_authenticated/create-team'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/workouts'
    | '/invite/$code'
    | '/_authenticated/'
    | '/_authenticated/_coach/attendance'
    | '/_authenticated/_coach/fleet'
    | '/_authenticated/_coach/lineup-builder'
    | '/_authenticated/_coach/recruiting'
    | '/_authenticated/_coach/seat-racing'
    | '/_authenticated/_coach/training'
    | '/_authenticated/_coach/whiteboard'
    | '/_authenticated/_team/athletes'
    | '/_authenticated/team/$identifier'
    | '/_authenticated/workouts/$workoutId'
    | '/_authenticated/team/'
    | '/_authenticated/workouts/'
    | '/_authenticated/_coach/training_/sessions'
    | '/_authenticated/team/$identifier/dashboard'
    | '/_authenticated/team/$identifier/settings'
    | '/_authenticated/_coach/training_/sessions/$sessionId'
    | '/_authenticated/_coach/training_/sessions/$sessionId/live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  GoodbyeRoute: typeof GoodbyeRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goodbye': {
      id: '/goodbye'
      path: '/goodbye'
      fullPath: '/goodbye'
      preLoaderRoute: typeof GoodbyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create-team': {
      id: '/_authenticated/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof AuthenticatedCreateTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_team': {
      id: '/_authenticated/_team'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_coach': {
      id: '/_authenticated/_coach'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workouts/': {
      id: '/_authenticated/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthenticatedWorkoutsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workouts/$workoutId': {
      id: '/_authenticated/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof AuthenticatedWorkoutsWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/team/$identifier': {
      id: '/_authenticated/team/$identifier'
      path: '/team/$identifier'
      fullPath: '/team/$identifier'
      preLoaderRoute: typeof AuthenticatedTeamIdentifierRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_team/athletes': {
      id: '/_authenticated/_team/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AuthenticatedTeamAthletesRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
    '/_authenticated/_coach/whiteboard': {
      id: '/_authenticated/_coach/whiteboard'
      path: '/whiteboard'
      fullPath: '/whiteboard'
      preLoaderRoute: typeof AuthenticatedCoachWhiteboardRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/training': {
      id: '/_authenticated/_coach/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedCoachTrainingRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/seat-racing': {
      id: '/_authenticated/_coach/seat-racing'
      path: '/seat-racing'
      fullPath: '/seat-racing'
      preLoaderRoute: typeof AuthenticatedCoachSeatRacingRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/recruiting': {
      id: '/_authenticated/_coach/recruiting'
      path: '/recruiting'
      fullPath: '/recruiting'
      preLoaderRoute: typeof AuthenticatedCoachRecruitingRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/lineup-builder': {
      id: '/_authenticated/_coach/lineup-builder'
      path: '/lineup-builder'
      fullPath: '/lineup-builder'
      preLoaderRoute: typeof AuthenticatedCoachLineupBuilderRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/fleet': {
      id: '/_authenticated/_coach/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedCoachFleetRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/attendance': {
      id: '/_authenticated/_coach/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedCoachAttendanceRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/team/$identifier/settings': {
      id: '/_authenticated/team/$identifier/settings'
      path: '/settings'
      fullPath: '/team/$identifier/settings'
      preLoaderRoute: typeof AuthenticatedTeamIdentifierSettingsRouteImport
      parentRoute: typeof AuthenticatedTeamIdentifierRoute
    }
    '/_authenticated/team/$identifier/dashboard': {
      id: '/_authenticated/team/$identifier/dashboard'
      path: '/dashboard'
      fullPath: '/team/$identifier/dashboard'
      preLoaderRoute: typeof AuthenticatedTeamIdentifierDashboardRouteImport
      parentRoute: typeof AuthenticatedTeamIdentifierRoute
    }
    '/_authenticated/_coach/training_/sessions': {
      id: '/_authenticated/_coach/training_/sessions'
      path: '/training/sessions'
      fullPath: '/training/sessions'
      preLoaderRoute: typeof AuthenticatedCoachTrainingSessionsRouteImport
      parentRoute: typeof AuthenticatedCoachRoute
    }
    '/_authenticated/_coach/training_/sessions/$sessionId': {
      id: '/_authenticated/_coach/training_/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/training/sessions/$sessionId'
      preLoaderRoute: typeof AuthenticatedCoachTrainingSessionsSessionIdRouteImport
      parentRoute: typeof AuthenticatedCoachTrainingSessionsRoute
    }
    '/_authenticated/_coach/training_/sessions/$sessionId/live': {
      id: '/_authenticated/_coach/training_/sessions/$sessionId/live'
      path: '/live'
      fullPath: '/training/sessions/$sessionId/live'
      preLoaderRoute: typeof AuthenticatedCoachTrainingSessionsSessionIdLiveRouteImport
      parentRoute: typeof AuthenticatedCoachTrainingSessionsSessionIdRoute
    }
  }
}

interface AuthenticatedCoachTrainingSessionsSessionIdRouteChildren {
  AuthenticatedCoachTrainingSessionsSessionIdLiveRoute: typeof AuthenticatedCoachTrainingSessionsSessionIdLiveRoute
}

const AuthenticatedCoachTrainingSessionsSessionIdRouteChildren: AuthenticatedCoachTrainingSessionsSessionIdRouteChildren =
  {
    AuthenticatedCoachTrainingSessionsSessionIdLiveRoute:
      AuthenticatedCoachTrainingSessionsSessionIdLiveRoute,
  }

const AuthenticatedCoachTrainingSessionsSessionIdRouteWithChildren =
  AuthenticatedCoachTrainingSessionsSessionIdRoute._addFileChildren(
    AuthenticatedCoachTrainingSessionsSessionIdRouteChildren,
  )

interface AuthenticatedCoachTrainingSessionsRouteChildren {
  AuthenticatedCoachTrainingSessionsSessionIdRoute: typeof AuthenticatedCoachTrainingSessionsSessionIdRouteWithChildren
}

const AuthenticatedCoachTrainingSessionsRouteChildren: AuthenticatedCoachTrainingSessionsRouteChildren =
  {
    AuthenticatedCoachTrainingSessionsSessionIdRoute:
      AuthenticatedCoachTrainingSessionsSessionIdRouteWithChildren,
  }

const AuthenticatedCoachTrainingSessionsRouteWithChildren =
  AuthenticatedCoachTrainingSessionsRoute._addFileChildren(
    AuthenticatedCoachTrainingSessionsRouteChildren,
  )

interface AuthenticatedCoachRouteChildren {
  AuthenticatedCoachAttendanceRoute: typeof AuthenticatedCoachAttendanceRoute
  AuthenticatedCoachFleetRoute: typeof AuthenticatedCoachFleetRoute
  AuthenticatedCoachLineupBuilderRoute: typeof AuthenticatedCoachLineupBuilderRoute
  AuthenticatedCoachRecruitingRoute: typeof AuthenticatedCoachRecruitingRoute
  AuthenticatedCoachSeatRacingRoute: typeof AuthenticatedCoachSeatRacingRoute
  AuthenticatedCoachTrainingRoute: typeof AuthenticatedCoachTrainingRoute
  AuthenticatedCoachWhiteboardRoute: typeof AuthenticatedCoachWhiteboardRoute
  AuthenticatedCoachTrainingSessionsRoute: typeof AuthenticatedCoachTrainingSessionsRouteWithChildren
}

const AuthenticatedCoachRouteChildren: AuthenticatedCoachRouteChildren = {
  AuthenticatedCoachAttendanceRoute: AuthenticatedCoachAttendanceRoute,
  AuthenticatedCoachFleetRoute: AuthenticatedCoachFleetRoute,
  AuthenticatedCoachLineupBuilderRoute: AuthenticatedCoachLineupBuilderRoute,
  AuthenticatedCoachRecruitingRoute: AuthenticatedCoachRecruitingRoute,
  AuthenticatedCoachSeatRacingRoute: AuthenticatedCoachSeatRacingRoute,
  AuthenticatedCoachTrainingRoute: AuthenticatedCoachTrainingRoute,
  AuthenticatedCoachWhiteboardRoute: AuthenticatedCoachWhiteboardRoute,
  AuthenticatedCoachTrainingSessionsRoute:
    AuthenticatedCoachTrainingSessionsRouteWithChildren,
}

const AuthenticatedCoachRouteWithChildren =
  AuthenticatedCoachRoute._addFileChildren(AuthenticatedCoachRouteChildren)

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamAthletesRoute: typeof AuthenticatedTeamAthletesRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamAthletesRoute: AuthenticatedTeamAthletesRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedWorkoutsRouteChildren {
  AuthenticatedWorkoutsWorkoutIdRoute: typeof AuthenticatedWorkoutsWorkoutIdRoute
  AuthenticatedWorkoutsIndexRoute: typeof AuthenticatedWorkoutsIndexRoute
}

const AuthenticatedWorkoutsRouteChildren: AuthenticatedWorkoutsRouteChildren = {
  AuthenticatedWorkoutsWorkoutIdRoute: AuthenticatedWorkoutsWorkoutIdRoute,
  AuthenticatedWorkoutsIndexRoute: AuthenticatedWorkoutsIndexRoute,
}

const AuthenticatedWorkoutsRouteWithChildren =
  AuthenticatedWorkoutsRoute._addFileChildren(
    AuthenticatedWorkoutsRouteChildren,
  )

interface AuthenticatedTeamIdentifierRouteChildren {
  AuthenticatedTeamIdentifierDashboardRoute: typeof AuthenticatedTeamIdentifierDashboardRoute
  AuthenticatedTeamIdentifierSettingsRoute: typeof AuthenticatedTeamIdentifierSettingsRoute
}

const AuthenticatedTeamIdentifierRouteChildren: AuthenticatedTeamIdentifierRouteChildren =
  {
    AuthenticatedTeamIdentifierDashboardRoute:
      AuthenticatedTeamIdentifierDashboardRoute,
    AuthenticatedTeamIdentifierSettingsRoute:
      AuthenticatedTeamIdentifierSettingsRoute,
  }

const AuthenticatedTeamIdentifierRouteWithChildren =
  AuthenticatedTeamIdentifierRoute._addFileChildren(
    AuthenticatedTeamIdentifierRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
  AuthenticatedCreateTeamRoute: typeof AuthenticatedCreateTeamRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTeamIdentifierRoute: typeof AuthenticatedTeamIdentifierRouteWithChildren
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCoachRoute: AuthenticatedCoachRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
  AuthenticatedCreateTeamRoute: AuthenticatedCreateTeamRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTeamIdentifierRoute:
    AuthenticatedTeamIdentifierRouteWithChildren,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  GoodbyeRoute: GoodbyeRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
