/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/_team'
import { Route as AuthenticatedWorkoutsIndexRouteImport } from './routes/_authenticated/workouts.index'
import { Route as AuthenticatedWorkoutsWorkoutIdRouteImport } from './routes/_authenticated/workouts.$workoutId'
import { Route as AuthenticatedTeamAthletesRouteImport } from './routes/_authenticated/_team/athletes'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/_team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkoutsIndexRoute =
  AuthenticatedWorkoutsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedWorkoutsWorkoutIdRoute =
  AuthenticatedWorkoutsWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => AuthenticatedWorkoutsRoute,
  } as any)
const AuthenticatedTeamAthletesRoute =
  AuthenticatedTeamAthletesRouteImport.update({
    id: '/athletes',
    path: '/athletes',
    getParentRoute: () => AuthenticatedTeamRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/athletes': typeof AuthenticatedTeamAthletesRoute
  '/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/workouts/': typeof AuthenticatedWorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/': typeof AuthenticatedIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/athletes': typeof AuthenticatedTeamAthletesRoute
  '/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/workouts': typeof AuthenticatedWorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/_team': typeof AuthenticatedTeamRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRouteWithChildren
  '/invite/$code': typeof InviteCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/_team/athletes': typeof AuthenticatedTeamAthletesRoute
  '/_authenticated/workouts/$workoutId': typeof AuthenticatedWorkoutsWorkoutIdRoute
  '/_authenticated/workouts/': typeof AuthenticatedWorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile'
    | '/settings'
    | '/workouts'
    | '/invite/$code'
    | '/athletes'
    | '/workouts/$workoutId'
    | '/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/'
    | '/profile'
    | '/settings'
    | '/invite/$code'
    | '/athletes'
    | '/workouts/$workoutId'
    | '/workouts'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/_team'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/workouts'
    | '/invite/$code'
    | '/_authenticated/'
    | '/_authenticated/_team/athletes'
    | '/_authenticated/workouts/$workoutId'
    | '/_authenticated/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteCodeRoute: typeof InviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_team': {
      id: '/_authenticated/_team'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workouts/': {
      id: '/_authenticated/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthenticatedWorkoutsIndexRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/workouts/$workoutId': {
      id: '/_authenticated/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof AuthenticatedWorkoutsWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedWorkoutsRoute
    }
    '/_authenticated/_team/athletes': {
      id: '/_authenticated/_team/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AuthenticatedTeamAthletesRouteImport
      parentRoute: typeof AuthenticatedTeamRoute
    }
  }
}

interface AuthenticatedTeamRouteChildren {
  AuthenticatedTeamAthletesRoute: typeof AuthenticatedTeamAthletesRoute
}

const AuthenticatedTeamRouteChildren: AuthenticatedTeamRouteChildren = {
  AuthenticatedTeamAthletesRoute: AuthenticatedTeamAthletesRoute,
}

const AuthenticatedTeamRouteWithChildren =
  AuthenticatedTeamRoute._addFileChildren(AuthenticatedTeamRouteChildren)

interface AuthenticatedWorkoutsRouteChildren {
  AuthenticatedWorkoutsWorkoutIdRoute: typeof AuthenticatedWorkoutsWorkoutIdRoute
  AuthenticatedWorkoutsIndexRoute: typeof AuthenticatedWorkoutsIndexRoute
}

const AuthenticatedWorkoutsRouteChildren: AuthenticatedWorkoutsRouteChildren = {
  AuthenticatedWorkoutsWorkoutIdRoute: AuthenticatedWorkoutsWorkoutIdRoute,
  AuthenticatedWorkoutsIndexRoute: AuthenticatedWorkoutsIndexRoute,
}

const AuthenticatedWorkoutsRouteWithChildren =
  AuthenticatedWorkoutsRoute._addFileChildren(
    AuthenticatedWorkoutsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTeamRoute: AuthenticatedTeamRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteCodeRoute: InviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
